const data=[
  {id:1,name:'Krnl',rating:5.0,avatar:'https://wearedevs.net/images/thumbnails/krnl.jpeg',version:'2.695.956',versionVng:'2.696.799',status:'Detected',statusVng:'Detected',platforms:['android'],downloadUrl:null,downloadVngUrl:null},
  {id:2,name:'Krnl',rating:5.0,avatar:'https://wearedevs.net/images/thumbnails/krnl.jpeg',version:'2.695',versionVng:'2.697',status:'Detected',statusVng:'Detected',platforms:['ios'],downloadUrl:null,downloadVngUrl:null},
  {id:3,name:'Arceus X NEO',rating:4.5,avatar:'https://files.catbox.moe/y8ddt5.png',version:'2.703.1353',versionVng:'2.703.1353',status:'online',statusVng:'online',platforms:['android'],downloadUrl:'https://android.spdmteam.com/',downloadVngUrl:'https://www.ngocbonggaming.com/2025/09/link-tai-arceus-vng-androi.html'},
  {id:4,name:'Delta',rating:4.9,avatar:'https://deltaexploits.gg/assets/favicon.ico',version:'2.704.1059',versionVng:'2.704.1059',status:'online',statusVng:'online',platforms:['ios'],downloadUrl:'https://gloopup.net/Delta/ios/',downloadVngUrl:'https://www.mediafire.com/file/8t0pjsxr5ykekdm/DeltaVN+V49+HuyMythic.ipa/file'},
  {id:5,name:'Codex',rating:4.8,avatar:'https://files.catbox.moe/s6hbqj.png',version:'2.703.1353',versionVng:'2.703.1353',status:'online',statusVng:'online',platforms:['android'],downloadUrl:'https://gofile.io/d/UzbLud',downloadVngUrl:'https://www.ngocbonggaming.com/2025/09/link-tai-codex-vng-androi.html'},
  {id:6,name:'Codex',rating:4.8,avatar:'https://files.catbox.moe/s6hbqj.png',version:'2.674.782',versionVng:null,status:'offline',statusVng:null,platforms:['ios'],downloadUrl:'https://www.mediafire.com/file/7afzer5xxo1110n/Codex_2.674.782.ipa/file',downloadVngUrl:null},
  {id:7,name:'Delta',rating:4.9,avatar:'https://deltaexploits.gg/assets/favicon.ico',version:'2.703.1353',versionVng:'2.703.1353',status:'online',statusVng:'online',platforms:['android'],downloadUrl:'https://gloopup.net/Delta/android/',downloadVngUrl:'https://www.ngocbonggaming.com/2025/08/link-tai-delta-vng-androi-moi-nhat.html'},
  {id:8,name:'Arceus X NEO',rating:4.5,avatar:'https://files.catbox.moe/y8ddt5.png',version:'2.668.658',versionVng:null,status:'offline',statusVng:null,platforms:['ios'],downloadUrl:'https://ios.spdmteam.com/',downloadVngUrl:null},
  {id:9,name:'Trigon',rating:4.5,avatar:'https://img.upanh.moe/ynRPDwBx/81e69e89eab4.webp',version:'2.703.1352',versionVng:'2.703.1353',status:'online',statusVng:'online',platforms:['android'],downloadUrl:'https://trigonevo.com/download?os=android&fs=Mediafire',downloadVngUrl:'https://www.ngocbonggaming.com/2025/09/link-tai-clien-trigon-vng-androi.html'},
  {id:10,name:'Evon',rating:4.4,avatar:'https://evon.cc/favicon.png',version:'2.700.937',versionVng:null,status:'offline',statusVng:null,platforms:['android'],downloadUrl:'https://evon.cc/android/dl-a/Evon.apk',downloadVngUrl:null},
  {id:11,name:'Vega X',rating:4.4,avatar:'https://vegax.gg/assets/img/V_logo_white.png',version:'2.703.1352',versionVng:null,status:'online',statusVng:null,platforms:['android'],downloadUrl:'https://github.com/1f0yt/community/releases',downloadVngUrl:null},
  {id:12,name:'Cryptic',rating:4.4,avatar:'https://img.upanh.moe/ychnyqVn/e8578fff456f.png',version:'2.704.1060',versionVng:'2.703.1352',status:'online',statusVng:'online',platforms:['android'],downloadUrl:'https://www.mediafire.com/file/z1lophbifjti0g0/Cryptic_APK_2.704.1060.apk/file',downloadVngUrl:'https://www.mediafire.com/file/f4dqfrs1jgj5hbm/Cryptic_VNG_APK_2.703.1352.apk/file'},
  {id:13,name:'Cryptic',rating:4.4,avatar:'https://img.upanh.moe/ychnyqVn/e8578fff456f.png',version:'2.668.660',versionVng:null,status:'offline',statusVng:null,platforms:['ios'],downloadUrl:null,downloadVngUrl:null},

  {id:14,name:'Bunni.lol',rating:4.6,avatar:'https://files.catbox.moe/hd9264.webp',version:'8b8c34790f814a73',versionVng:null,status:'online',statusVng:null,platforms:['windows'],downloadUrl:'https://bom.so/nZIHJ5',downloadVngUrl:null},
  {id:15,name:'Swift',rating:4.8,avatar:'https://files.catbox.moe/5krpqt.webp',version:'89b6c70d8f7f42ac',versionVng:null,status:'offline',statusVng:null,platforms:['windows'],downloadUrl:'https://getswift.vip/',downloadVngUrl:null},
  {id:16,name:'Velocity',rating:4.4,avatar:'https://files.catbox.moe/tj6brv.png',version:'8b8c34790f814a73',versionVng:null,status:'online',statusVng:null,platforms:['windows'],downloadUrl:'https://gofile.io/d/qpOZtq',downloadVngUrl:null},
  {id:17,name:'Trigon',rating:4.2,avatar:'https://img.upanh.moe/ynRPDwBx/81e69e89eab4.webp',version:'889d2588b25a43d1',versionVng:null,status:'offline',statusVng:null,platforms:['windows'],downloadUrl:'https://trigonevo.com/download?os=windows&fs=mediafire',downloadVngUrl:null}
];
